name: CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Lint/Test/Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

      - name: Run tests
        run: npm run test:headless

      - name: Run build
        run: npm run build
